import random
kelimeler = ["gözəl","məlumat","problem","təmin","ayrılmaq","vaxt","su","istifadə","deyil","bax",
             "dərinizdən", "çox", "amma", "lirə", "oynamaq", "çiçək", "şəhər", "yüksək", "döyüş", "varlıq", "do",
             "güvən", "lazım", "müalicə", "vahid", "rahat", "soyuq", "orada", "kitab", "pay", "hesab", "bədən",
             'zəmin', 'aşdı', 'sistem', 'gözəl', 'çəkilmə', 'texnika', 'yanlaşma', 'il', 'tarix', 'dəqiq', 'bacı',
             "cərimə", "əgər", "halbuki", "qaytarmaq", "vermək", "var", "qalıq", "şəxs", "başqa", "dövr", "yenidən", "bunlar",
             "kitab", "hadisə", "olmaq", "sən", "dövlət", "ön", "ən çox", "baxmaq", "on", "belə", "bəzi", "başlamaq",
             "saxla", "bir-birini", "heç biri", "et", "su", "kimi", "dövlət", "sağ", "orta", "başqa", "böyük", "etmək",
             "yeni", "daha çox", "soruş", "onlar", "yandır", "hər ikisi", "həmişə", "səs", "anla", "yox", "saat", "necə",
'bir', 'və', 'olmaq', 'bu', 'üçün', 'o', 'mən', 'demək', 'çox', 'edmək', 'nə', 'bəyənmək', ' daha çox ', 'almaq',
             'var', 'öz', 'gəl', 'birlikdə', 'vermək', 'amma', 'sonra', ' qədər', 'yer', 'çox', 'insanlar', 'yox', 'hər ',
             'istəyirəm', 'il', 'çıxmaq', 'görmək', 'gün', 'biz', 'getmək', 'işləmək', 'şey', 'zəng', 'o', 'bilmək', ' əl ', 'zaman',
             'ya', 'uşaq', 'iki', 'bax', 'iş', 'in', 'böyük', 'yox', 'başlanğıc', 'yol', 'qal', 'niyə', 'sən ',
             "mövzu", "olmaq", "yaxşı", "qadın", "ev", "olmaq", "olmaq", "demək", "göz", "lazım", "dünya",
             'baş', 'dövlət', 'yan', 'keçmək', 'siz', 'onlar', 'yeni', 'əvvəl', 'başqa', 'dövlət', 'orta', 'su', 'girmək ', 'ölkə',
             'yemək', 'heç', 'hətta', 'necə', 'hamısı', 'əleyhinə', 'tapmaq', 'belə', 'yaşamaq', 'düşünmək', 'eyni', 'içmək', 'lakin'',
             'şəxs', 'onlar', 'və ya', 'birinci', 'görə', 'ön', 'son', 'bir', 'forma', 'vacib', 'üz', 'hər ikisi', ' göstərmək ', 'etmək','qalx', 'hətta', 'təsir', 'inkişaf', 'keçmək', 'bədən', 'düşüncə', 'milyon', 'oynamaq', 'dəyişiklik', 'əsas',
             'yaratmaq', 'çatmaq', 'düşünmək', 'keçmək', 'mədəniyyət', 'qurmaq', 'amma', 'buna', 'rəsm etmək', 'işıq', 'içmək',
             'xanım', 'xidmət', 'ehtiyac', 'nöqtə', 'istiqamət', 'bəli', 'oyun', 'artırma', 'yenidən yükləmə', 'proses', 'qısa', 'asan',
             'hansı', 'qiymət', 'əslində', 'qəbul edirəm', 'orada', 'diqqət', 'uzaq', 'kompüter', 'gələcək', 'görünür',
             'məsələn', 'oğul', 'dinləmə', 'uyğun', 'lirə', 'istehsal', 'dəqiqə', 'unutmaq', 'gəzmək', 'belə', 'pis',
             'avtomobil', 'ağız', 'hiss et', 'tətbiq et', 'hələ', 'nümunə', 'çox', 'baxmaq', 'dərəcə', 'mümkün', 'belə',
             'divar', 'on', 'incəsənət', 'əsas', 'xəstəlik', 'tələbə', 'televiziya', 'metod', 'masa', 'ölüm', 'komanda', 'üst',
             'baş', 'musiqi', 'ayrılmaq', 'enerji', 'universitet', 'idman', 'mehriban', 'ruh', 'baxmayaraq', 'hissə', 'ölüm',
'daimi', 'sağlamlıq', 'müxtəlif', 'bundan', 'hiss', 'halbuki', 'səhər', 'internet', 'texniki', 'çıxış',
             'mərkəz', 'ekologiya', 'əvəzində', 'səviyyə', 'kənd', 'idarəetmə', 'aşağı', 'cavab', 'lay', 'torpaq','', 'axşam',
             'araşdırma', 'götürmək', 'iştirak', 'əks halda', 'qurmaq', 'ödəmək', 'sanki', 'qan', 'xəstə', 'şəhər', 'enmək',
             'indiki', 'məlum', 'həftə', 'trafik', 'hesab', 'avtomobil', 'yadplanetli', 'davranış', 'mətbəx', 'şəhər', 'bəzən',
             'müəyyən', 'ayrı', 'qiymət', 'haqqında', 'çıxarmaq', 'qol', 'yalnız', 'hazırlamaq', 'şüşə', 'nəhayət', 'yavaş',
             'zəruri', 'əhəmiyyət', 'ər', 'yalan', 'aktiv', 'sənət', 'faiz', 'siz', 'satış', 'in', 'təbii', 'sahib olmaq',
             'iqtisadi', 'ağrı', 'yox', 'qorumaq', 'mərtəbə', 'iqtisadiyyat', 'ümumi', 'müəyyən et', 'foto', 'heyvan', 'müharibə',
             'mal', 'saç', 'itirmək', 'qalıq', 'dəyişiklik', 'dörd', 'həqiqətən', 'səhifə', 'texnologiya', 'qurum', 'beş','ağlama', 'əlaqəli', 'konsept', 'artım', 'fəaliyyət', 'zərər', 'dərin', 'lounge', 'bir', 'kəsilmiş',
             'izləmək', 'birdən', 'tutmaq', 'saymaq', 'toplamaq', 'ütmək', 'qışqırmaq', 'məsuliyyət', 'hərəkət etmək',
             'məktub', 'soyuq', 'canlı', 'idikeylem', 'maşın', 'istifadə etmək', 'köhnə', 'boş', 'görəsən', 'kibrit', 'menecer',
             'gətirildi', 'metre', 'saxlanıldı', 'keyfiyyət', 'bitki', 'dəyişiklik', 'tibb', 'kredit', 'qanun', 'uğurlu',
             'bir', 'imkan', 'cəza', 'hər şey', 'yoxlama', 'top', 'ekspert', 'doldurma', 'kanal', 'boşluq', 'uyğun',
             'illik', 'buna görə', 'yazmaq', 'aid olmaq', 'barmaq', 'saymaq', 'atmaq', 'müəyyən etmək', 'normal', 'hele',
             'prinsip', 'qırmızı', 'rol', 'mahnı', 'heyət', 'hazır', 'oxşar', 'nəsə', 'müəllim', 'oğlan', 'gündəlik', 'siyasət',
             'cinayət', 'niyə', 'səhnə', 'ilişib', 'özəl', 'oturmaq', 'saxla', 'artist', 'üstünlük', 'uzamaq', 'səhnə',
'əlavə et', 'meşə', 'ayrı', 'sifariş', 'faiz', 'adətən', 'həmişə', 'hekayə', 'hüceyrə', 'orada', 'roman',
             'vergi', 'yanmaq', 'qardaş', 'mətbuat', 'dəstək', 'geyinmək', 'səhv', 'limit', 'birlik', 'iş', 'görüşmək',
             'yarım', 'yetər', 'fərdi', 'qaranlıq', 'avtobus', 'sənaye', 'körpə', 'vətəndaş', 'nazir', 'zaman', 'millət',
             'reklam', 'yüksəlmə', 'ölçü', 'jurnal', 'inflyasiya', 'sosial', 'kimsə', 'keçmiş', 'xəstəxana', 'varlıq',
             'görüş', 'jurnalist', 'daxili', 'iman', 'keyfiyyət', 'bitdi', 'bitiş', 'yerləşin', 'giriş', 'rahat',
             'cəmi', 'birlikdə', 'mağaza', 'gizli', 'oxşar', 'dəri', 'çevirmək', 'döyüş', 'problem', 'xidmət', 'müalicə',
             'yaşıl', 'nazirlik', 'təzyiq', 'reaksiya', 'cümlə', 'istək', 'azadlıq', 'yenidən', 'şəxsiyyət', 'məsələ', 'üçüncü',
             'müəyyən et', 'qiymətləndirmək', 'maraqlı', 'sürücü', 'süd', 'tutmaq', 'eşya', 'beynəlxalq', 'namizəd',
             ]


def kelime_sec():
    return random.choice(kelimeler)