import random
kelimeler = ["gözəl", "məlumat", "problem", "təmin etmək", "getmək", "vaxt", "su", "etmək", "yox", "görmək",
               "dərinizdən", "ən çox", "amma", "lirə", "oynamaq", "çiçək", "şəhər", "yüksək", "döyüş", "varlıq", "do",
               "güvən", "lazım", "müalicə", "vahid", "rahat", "soyuq", "orada", "kitab", "pay", "hesab", "bədən",
               'zəmin', 'aşdı', 'sistem', 'gözəl', 'çəkilmə', 'texnika', 'yanlaşma', 'il', 'tarix', 'dəqiq', 'bacı',
               "cərimə", "əgər", "halbuki", "qaytarmaq", "vermək", "var", "qalıq", "şəxs", "başqa", "dövr", "yenidən", "bunlar",
               "kitab", "hadisə", "olmaq", "sən", "dövlət", "ön", "ən çox", "baxmaq", "on", "belə", "bəzi", "başlamaq",
               "saxla", "bir-birini", "heç biri", "et", "su", "kimi", "dövlət", "sağ", "orta", "başqa", "böyük", "etmək",
               "yeni", "daha çox", "soruş", "onlar", "yandır", "hər ikisi", "həmişə", "səs", "anla", "yox", "saat", "necə",
               'bir', 'və', 'olmaq', 'bu', 'üçün', 'o', 'mən', 'demək', 'çox', 'edmək', 'nə', 'bəyənmək', ' daha çox ', 'almaq',
               'var', 'öz', 'gəl', 'birlikdə', 'vermək', 'amma', 'sonra', 'nə qədər', 'yer', 'çox', 'insanlar', 'yox', 'hər ',
               'istəyirəm', 'il', 'çıxmaq', 'görmək', 'gün', 'biz', 'getmək', 'işləmək', 'şey', 'zəng etmək', 'o', 'bilmək', ' əl ', 'zaman',
               'ya', 'uşaq', 'iki', 'bax', 'iş', 'in', 'böyük', 'yox', 'başlanğıc', 'yol', 'qal', 'niyə', 'sən ',
               "mövzu", "olmaq", "yaxşı", "qadın", "ev", "olmaq", "olmaq", "demək", "göz", "lazım", "dünya",
               'baş', 'dövlət', 'yan', 'keçmək', 'siz', 'onlar', 'yeni', 'əvvəl', 'başqa', 'dövlət', 'orta', 'su', 'girmək ' ', 'ölkə',
               'yemək', 'heç', 'hətta', 'necə', 'hamısı', 'əleyhinə', 'tapmaq', 'belə', 'yaşamaq', 'düşünmək', 'eyni', 'içmək', 'lakin'',
               'şəxs', 'onlar', 'və ya', 'birinci', 'görə', 'ön', 'son', 'bir', 'forma', 'vacib', 'üz', 'hər ikisi', ' göstərmək ', 'etmək',
               'alt', 'gətir', 'istifadə', 'çünki', 'yan', 'indi', 'kişi', 'onun', 'başqası', 'indi', 'üstü', 'səs', 'həmişə ',
               'sağ', 'durmaq', 'qız', 'hamısı', 'cəlb etmək', 'danışmaq', 'pul', 'anlamaq', 'ana', 'az', 'bəzi', 'ata', 'həyat ' ',
               'yalnız', 'kiçik', 'daha çox', 'məlumat', 'an', 'soruş', 'o', 'o', 'yenidən', 'təmin et', 'nəticə', 'istifadə', 'xarici ' ',
               'ad', 'o', 'müddət', 'döndürmək', 'yanmaq', 'oturmaq', 'demək', 'çıxmaq', 'dərhal', 'vaxt', 'yaş', 'problem', ' dövlət ',
               'var', 'sətir', 'yazmaq', 'faiz', 'ay', 'atmaq', 'tutmaq', 'bu', 'hadisə', 'düşmək', 'eşitmək', 'söz', 'gözəl' ',
               'sevmək', 'bir az', 'çətin', 'almaq', 'o', 'qoymaq', 'birə', 'sistem', 'birlikdə', 'veriləcək', 'kim' , 'alınacaq', 'gənc',
               'qapı', 'kitab', 'on', 'burada', 'gecə', 'alan', 'bir-birimizə', 'burada', 'gözləyin', 'uzun', 'yox', 'bu gün', ' dövr'',
               'dost', 'məhsul', 'ailə', 'üç', 'təhsil', 'kişi', 'hamı', 'güc', 'bəlkə', 'real', 'tam', 'əlaqəli', 'münasibət ',
               'ekologiya', 'köhnə', 'axtarış', 'həyat', 'ictimai', 'yaxınlıqda', 'küçə', 'squire', 'tarix', 'mülkiyyət', 'bölmə', 'özəl', 'səbəb ' ',
               'heç kim', 'çox deyil', 'əgər', 'lazımdır', 'xüsusən', 'orta', 'yüksək', 'bank', 'bir dəfə', 'ayaq', 'hərəkət et', 'geri', ' cəmiyyət'',
               'alət', 'element', 'növ', 'qərar', 'bax', 'hava', 'nömrə', 'fərqli', 'qrup', 'otaq', 'forma', 'forma', 'xəbərlər ' ',
               'allah', 'həmçinin', 'gələn', 'az', 'sual', 'geri', 'qazanma', 'poçt', 'məktəb', 'açıq', 'öyrən', 'sürüş',
               'dil', 'şirkət', 'mənbə', 'bitir', 'proqram', 'davam et', 'hərəkət et', 'rəng', 'açmaq', 'sağ', 'inan',
               'təhsil', 'bucaq', 'parça', 'qəzet', 'yaratmaq', 'əlbəttə', 'dəyər', 'bilmək', 'struktur', 'doktor', 'gəlir',
               'tapşırıq', 'məqsəd', 'region', 'film', 'to', 'müştəri', 'artıq', 'telefon', 'təhsil', 'dəniz', 'ikinci',
               'qalx', 'hətta', 'təsir', 'inkişaf etmək', 'keçmək', 'bədən', 'düşüncə', 'milyon', 'oynamaq', 'dəyişiklik', 'əsas',
               'yaratmaq', 'çatmaq', 'düşünmək', 'keçmək', 'mədəniyyət', 'qurmaq', 'amma', 'buna', 'rəsm etmək', 'işıq', 'içmək',
               'xanım', 'xidmət', 'ehtiyac', 'nöqtə', 'istiqamət', 'bəli', 'oyun', 'artırma', 'yenidən yükləmə', 'proses', 'qısa', 'asan',
               'hansı', 'qiymət', 'əslində', 'qəbul edirəm', 'orada', 'diqqət', 'uzaq', 'kompüter', 'gələcək', 'görünür',
               'məsələn', 'oğul', 'dinləmə', 'uyğun', 'lirə', 'istehsal', 'dəqiqə', 'unutmaq', 'gəzmək', 'belə', 'pis',
               'avtomobil', 'ağız', 'hiss et', 'tətbiq et', 'hələ', 'nümunə', 'çox', 'baxmaq', 'dərəcə', 'mümkün', 'belə',
               'divar', 'on', 'incəsənət', 'əsas', 'xəstəlik', 'tələbə', 'televiziya', 'metod', 'masa', 'ölüm', 'komanda', 'üst',
               'baş', 'musiqi', 'ayrılmaq', 'enerji', 'universitet', 'idman', 'mehriban', 'ruh', 'baxmayaraq', 'hissə', 'ölüm',
               'daimi', 'sağlamlıq', 'müxtəlif', 'bundan', 'hiss', 'halbuki', 'səhər', 'internet', 'texniki', 'çıxış',
               'mərkəz', 'ekologiya', 'əvəzində', 'səviyyə', 'kənd', 'idarəetmə', 'aşağı', 'cavab', 'lay', 'torpaq','', 'axşam',
               'araşdırma', 'götürmək', 'iştirak etmək', 'əks halda', 'qurmaq', 'ödəmək', 'sanki', 'qan', 'xəstə', 'şəhər', 'enmək',
               'indiki', 'məlum', 'həftə', 'trafik', 'hesab', 'avtomobil', 'yadplanetli', 'davranış', 'mətbəx', 'şəhər', 'bəzən',
               'müəyyən', 'ayrı', 'qiymət', 'haqqında', 'çıxarmaq', 'qol', 'yalnız', 'hazırlamaq', 'şüşə', 'nəhayət', 'yavaş',
               'zəruri', 'əhəmiyyət', 'ər', 'yalan', 'aktiv', 'sənət', 'faiz', 'siz', 'satış', 'in', 'təbii', 'sahib olmaq',
               'iqtisadi', 'ağrı', 'yox', 'qorumaq', 'mərtəbə', 'iqtisadiyyat', 'ümumi', 'müəyyən et', 'foto', 'heyvan', 'müharibə',
               'mal', 'saç', 'itirmək', 'qalıq', 'dəyişiklik', 'dörd', 'həqiqətən', 'səhifə', 'texnologiya', 'qurum', 'beş',
               'sektor', 'geniş', 'kağız', 'ətir', 'sağ', 'isti', 'əsr', 'küçə', 'bazar', 'davam etmək', 'istifadə', 'sinif',
               'sevgi', 'doğulmuş', 'ağır', 'yenidən', 'günəş', 'siqaret', 'ağac', 'söz', 'bina', 'arvad', 'qaçmaq', 'partiya',' yataq ',
               'müəllif', 'qulaq', 'müəllim', 'səbəb', 'sol', 'yaxşı', 'yağ', 'çünki', 'başa düşmək', 'gəlmək', 'gülmək', 'qayda',
               'satmaq', 'şeir', 'göndərmək', 'uğur', 'möhkəm', 'hökumət', 'ürək', 'kəsmək', 'layihə', 'lazımdır', 'sürət', 'künc',
               'vur', 'model', 'balıq', 'bazar', 'baxış', 'burada', 'hazırla', 'miqdar', 'birinci', 'kvadrat', 'ölçü',
               'seçmək', 'tətbiq etmək', 'bağ', 'sevgi', 'çörək', 'boyu', 'qaçmaq', 'dolu', 'quruluş', 'demək', 'qorxu',
               'kömək', 'görüş', 'əşyalar', 'gözəl', 'it', 'məşhur', 'böyümək', 'ətrafında gəzmək', 'olduqca', 'üstəlik',
               'yaşamaq', 'ağ', 'istəmək', 'arxada', 'çalışmaq', 'qardaş', 'çəkilmə', 'harada', 'oğurluq', 'icazə', 'qorxu',
               'peşə', 'polis', 'yalnız', 'izah et', 'fikir', 'tez', 'pəncərə', 'işlə məşğul olmaq', 'daş', 'yanğın', 'fərq',
               'kifayətdir', 'ən çox', 'bəzi', 'şərt', 'qonşuluq', 'lazımdır', 'taxıl', 'istehsal etmək', 'üstündə', 'tutmaq', 'nazik',
               'neçə', 'ümumi', 'növ', 'şəkil', 'beri', 'dərs', 'sədr', 'counter', 'qurtulmaq', 'sayı', 'dəfə',
               'olmaq', 'qərb', 'başa düşmək', 'hər hansı', 'sinema', 'fərqli', 'hədəf', 'yuxu', 'dost', 'yanmaq',
               'anlayış', 'usta', 'mətbuat', 'kənar', 'nəzarət', 'flip', 'din', 'güclü', 'hələ', 'plan', 'beyin',
               'elektrik', 'arvad', 'on', 'ət', 'təmin edilmiş', 'deyiləcək', 'xətt', 'uçmaq', 'üzv', 'dəri', 'ruh',
               'əziz', 'yanaşma', 'proses', 'baxış', 'elm', 'irəli', 'ifadə', 'bədən', 'xatırla', 'qəza',
               'hərtərəfli', 'dağ', 'yaxın', 'addım', 'ciddi', 'həll', 'impress', 'bələdiyyə', 'inkişaf', 'seçki',
               'ağlama', 'əlaqəli', 'konsept', 'artım', 'fəaliyyət', 'zərər', 'dərin', 'lounge', 'bir növ', 'kəsilmiş',
               'izləmək', 'birdən', 'tutmaq', 'saymaq', 'toplamaq', 'ütmək', 'qışqırmaq', 'məsuliyyət', 'hərəkət etmək',
               'məktub', 'soyuq', 'canlı', 'idikeylem', 'maşın', 'istifadə et', 'köhnə', 'boş', 'görəsən', 'kibrit', 'menecer',
               'gətirildi', 'metr', 'saxlanıldı', 'keyfiyyət', 'bitki', 'dəyişiklik', 'tibb', 'kredit', 'qanun', 'uğur',
               'bir', 'imkan', 'cəza', 'hər şey', 'yoxlama', 'top', 'ekspert', 'doldurma', 'kanal', 'boşluq', 'uyğun',
               'illik', 'buna görə', 'yazmaq', 'aid olmaq', 'barmaq', 'saymaq', 'atmaq', 'müəyyən etmək', 'normal', 'hele',
               'prinsip', 'qırmızı', 'rol', 'mahnı', 'heyət', 'hazır', 'oxşar', 'nəsə', 'müəllim', 'oğlan', 'gündəlik', 'siyasət',
               'cinayət', 'niyə', 'səhnə', 'ilişib', 'özəl', 'oturmaq', 'saxla', 'artist', 'üstünlük', 'uzamaq', 'səhnə',
               'əlavə et', 'meşə', 'ayrı', 'sifariş', 'faiz', 'adətən', 'həmişə', 'hekayə', 'hüceyrə', 'orada', 'roman',
               'vergi', 'yanmaq', 'qardaş', 'mətbuat', 'dəstək', 'geyinmək', 'səhv', 'limit', 'birlik', 'iş', 'görüşmək',
               'yarım', 'yetər', 'fərdi', 'qaranlıq', 'avtobus', 'sənaye', 'körpə', 'vətəndaş', 'nazir', 'zaman', 'millət',
               'reklam', 'yüksəlmə', 'ölçü', 'jurnal', 'inflyasiya', 'sosial', 'kimsə', 'keçmiş', 'xəstəxana', 'varlıq',
               'görüş', 'jurnalist', 'daxili', 'iman', 'keyfiyyət', 'bitdi', 'bitiş', 'yerləşin', 'giriş', 'rahat',
               'cəmi', 'birlikdə', 'mağaza', 'gizli', 'oxşar', 'dəri', 'çevirmək', 'döyüş', 'problem', 'xidmət', 'müalicə',
               'yaşıl', 'nazirlik', 'təzyiq', 'reaksiya', 'cümlə', 'istək', 'azadlıq', 'yenidən', 'şəxsiyyət', 'məsələ', 'üçüncü',
               'müəyyən et', 'qiymətləndirmək', 'maraqlı', 'sürücü', 'süd', 'tutmaq', 'eşya', 'beynəlxalq', 'namizəd',
               'çəki', 'milyard', 'sağlam', 'sıxıntı', 'tanrı', 'rəftar', 'sosial', 'nəşriyyat', 'diqqətli', 'son dərəcə',
               'topla', 'investisiya et', 'işıqlandırmaq', 'qarışdırmaq', 'təhlükə', 'zaman', 'dairə', 'imkan', 'proses', 'qarışdırmaq',
               'töhfə', 'hekayə', 'tamamilə', 'təyyarə', 'cavab', 'təbiət', 'evlənmək', 'burun', 'faiz', 'əlbəttə', 'işçi', 'iş',
               'qısaca', 'mağaza', 'media', 'çünki', 'artım', 'çıxarmaq', 'ictimai', 'sığorta', 'yay', 'ürək', 'sənəd',
               'səy', 'hər gün', 'ekspress', 'risk', 'danışma', 'söz', 'demokratiya', 'duz', 'məscid', 'yaş', 'aşağı',
               'ətrafında', 'tezliklə', 'imkan', 'orqan', 'öldürmək', 'başqa', 'il', 'çürümək', 'baxmaq', 'meyvə', 'asmaq',
               'şirin', 'ayaq', 'dəyişiklik', 'qanun', 'külək', 'respublika', 'təkmilləşdirmək', 'üslub', 'yeddi', 'azalmaq',
               'qoşun', 'mobil telefon', 'ünsiyyət', 'menecer', 'otel', 'qaçmaq', 'zövq almaq', 'sürüş', 'təhlükəsizlik', 'qanun',
               'et', 'modern', 'oxumaq', 'tüfəng', 'tələb', 'ulduz', 'intensiv', 'əsgər', 'sadə', 'adlanacaq', 'qaz',
               'tətbiq', 'istehsal', 'bəyanat', 'qida', 'dünən', 'bax', 'haqqında', 'alış-veriş', 'şüur', 'çərçivə',
               'lazımdır', 'mövcuddur', 'istehlakçı', 'uzatmaq', 'to', 'at', 'qoşulmaq', 'məsələn', 'demək olar', 'sayt',
               'kömək', 'bacı', 'çiçək', 'hamısı', 'hörmət', 'ödəmək', 'istedad', 'ağırlıq', 'pay', 'çətin', 'bundan başqa',
               'çay', 'gedər', 'əmin', 'zəngin', 'heç vaxt', 'söz', 'təşkilat', 'ticarət', 'make out', 'boyun', 'cihaz',
               'balans', 'gedəcək', 'geri', 'çünki', 'qəhvə', 'əzələ', 'montaj', 'başqa', 'işlətmək', 'ünvan', 'müəyyən etmək',
               'paşa', 'istilik', 'ok', 'güvən', 'marka', 'yarpaq', 'fayda', 'yaymaq', 'axan', 'çəkmək', 'düşünmək',
               'ürək', 'arzu', 'tərəqqi', 'şərab', 'yuxarıda', 'qızıl', 'arandırmaq', 'almaq', 'təqdim etmək', 'təmiz',
               'vitamin', 'əlavə', 'gec', 'aktyor', 'yumurta', 'həddindən artıq', 'hərəkət', 'istəyək', 'kəsmə', 'böhran', 'vahid',
               'söndür'
             ]


def kelime_sec():
    return random.choice(kelimeler)